import type {
  LegacyZone as Zone,
  LegacyAlert as Alert,
  LegacyPilgrim as Pilgrim,
  LegacyLostFoundCase as LostFoundCase,
  LegacyAmbulance as Ambulance,
  Agent,
  AgentInvocationLog,
  GhatCondition,
} from './types'

export const ZONES: Zone[] = [
  {
    zoneId: 'z-001',
    name: 'Ramkund Main Ghat',
    city: 'nashik',
    ghatName: 'Ramkund',
    currentDensity: 6.8,
    capacity: 5000,
    currentCount: 4100,
    status: 'red',
    isHeld: true,
    lastUpdated: new Date(Date.now() - 120000).toISOString(),
    cameraCount: 12,
    coordinates: { lat: 19.9975, lng: 73.7898 },
  },
  {
    zoneId: 'z-002',
    name: 'Ramkund East Entry',
    city: 'nashik',
    currentDensity: 4.2,
    capacity: 3000,
    currentCount: 2100,
    status: 'yellow',
    isHeld: false,
    lastUpdated: new Date(Date.now() - 95000).toISOString(),
    cameraCount: 8,
    coordinates: { lat: 19.9978, lng: 73.7912 },
  },
  {
    zoneId: 'z-003',
    name: 'Ramkund West Corridor',
    city: 'nashik',
    currentDensity: 2.1,
    capacity: 4000,
    currentCount: 1400,
    status: 'green',
    isHeld: false,
    lastUpdated: new Date(Date.now() - 80000).toISOString(),
    cameraCount: 6,
    coordinates: { lat: 19.9971, lng: 73.7884 },
  },
  {
    zoneId: 'z-004',
    name: 'Ahilya Ghat',
    city: 'nashik',
    ghatName: 'Ahilya Ghat',
    currentDensity: 5.5,
    capacity: 3500,
    currentCount: 2800,
    status: 'yellow',
    isHeld: false,
    lastUpdated: new Date(Date.now() - 60000).toISOString(),
    cameraCount: 9,
    coordinates: { lat: 19.9963, lng: 73.7871 },
  },
  {
    zoneId: 'z-005',
    name: 'Sunder Narayan Ghat',
    city: 'nashik',
    ghatName: 'Sunder Narayan',
    currentDensity: 1.8,
    capacity: 2500,
    currentCount: 700,
    status: 'green',
    isHeld: false,
    lastUpdated: new Date(Date.now() - 150000).toISOString(),
    cameraCount: 5,
    coordinates: { lat: 19.9955, lng: 73.7858 },
  },
  {
    zoneId: 'z-006',
    name: 'Sadhugram Zone A',
    city: 'nashik',
    currentDensity: 3.2,
    capacity: 8000,
    currentCount: 4200,
    status: 'green',
    isHeld: false,
    lastUpdated: new Date(Date.now() - 200000).toISOString(),
    cameraCount: 16,
    coordinates: { lat: 19.9988, lng: 73.7812 },
  },
  {
    zoneId: 'z-007',
    name: 'Sadhugram Zone B',
    city: 'nashik',
    currentDensity: 2.8,
    capacity: 7000,
    currentCount: 3100,
    status: 'green',
    isHeld: false,
    lastUpdated: new Date(Date.now() - 180000).toISOString(),
    cameraCount: 14,
    coordinates: { lat: 19.9995, lng: 73.7800 },
  },
  {
    zoneId: 'z-008',
    name: 'Nashik Bus Terminal',
    city: 'nashik',
    currentDensity: 4.9,
    capacity: 6000,
    currentCount: 4200,
    status: 'yellow',
    isHeld: false,
    lastUpdated: new Date(Date.now() - 45000).toISOString(),
    cameraCount: 20,
    coordinates: { lat: 20.0058, lng: 73.7921 },
  },
  {
    zoneId: 'z-009',
    name: 'Kushavart Kund Core',
    city: 'trimbakeshwar',
    ghatName: 'Kushavart Kund',
    currentDensity: 7.9,
    capacity: 500,
    currentCount: 480,
    status: 'black',
    isHeld: true,
    lastUpdated: new Date(Date.now() - 30000).toISOString(),
    cameraCount: 8,
    coordinates: { lat: 19.9333, lng: 73.5299 },
  },
  {
    zoneId: 'z-010',
    name: 'Kushavart Approach West',
    city: 'trimbakeshwar',
    currentDensity: 6.1,
    capacity: 1200,
    currentCount: 980,
    status: 'red',
    isHeld: false,
    lastUpdated: new Date(Date.now() - 40000).toISOString(),
    cameraCount: 6,
    coordinates: { lat: 19.9321, lng: 73.5287 },
  },
  {
    zoneId: 'z-011',
    name: 'Trimbakeshwar Temple Precinct',
    city: 'trimbakeshwar',
    currentDensity: 5.4,
    capacity: 2000,
    currentCount: 1600,
    status: 'red',
    isHeld: false,
    lastUpdated: new Date(Date.now() - 55000).toISOString(),
    cameraCount: 10,
    coordinates: { lat: 19.9346, lng: 73.5305 },
  },
  {
    zoneId: 'z-012',
    name: 'Trimbak Parking Hub',
    city: 'trimbakeshwar',
    currentDensity: 2.3,
    capacity: 5000,
    currentCount: 1800,
    status: 'green',
    isHeld: false,
    lastUpdated: new Date(Date.now() - 300000).toISOString(),
    cameraCount: 12,
    coordinates: { lat: 19.9298, lng: 73.5271 },
  },
]

export const ALERTS: Alert[] = [
  {
    alertId: 'a-001',
    type: 'stampede',
    severity: 'critical',
    zoneId: 'z-009',
    zoneName: 'Kushavart Kund Core',
    city: 'trimbakeshwar',
    title: 'Stampede risk — Kushavart Kund Core exceeds 7.5 p/sqm',
    description:
      'Crowd density has reached 7.9 p/sqm at Kushavart Kund Core, significantly exceeding the critical 7.5 threshold. Immediate crowd dispersal required.',
    agentSource: 'CrowdSentinel',
    status: 'open',
    createdAt: new Date(Date.now() - 180000).toISOString(),
    sopSteps: [
      'Activate emergency PA system at Kushavart Kund',
      'Deploy rapid response team (RRT) — minimum 20 personnel',
      'Initiate crowd flow reversal from all entry points',
      'Notify NDRF team stationed at Trimbak base',
      'Contact district collector for emergency declaration',
      'Divert incoming pilgrims via Route B and C',
    ],
  },
  {
    alertId: 'a-002',
    type: 'crowd_surge',
    severity: 'critical',
    zoneId: 'z-009',
    zoneName: 'Kushavart Kund Core',
    city: 'trimbakeshwar',
    title: 'Entry hold activated — 480/500 capacity at Kushavart Kund',
    description:
      'Automated entry hold triggered. Zone at 96% of safe capacity. All entry points to Kushavart Kund are now closed.',
    agentSource: 'CommandBridge',
    status: 'responding',
    createdAt: new Date(Date.now() - 240000).toISOString(),
    acknowledgedBy: 'Rajesh Patil',
    sopSteps: [
      'Verify hold status on all 4 entry gates',
      'Deploy personnel to enforce hold physically',
      'Activate overflow management at Trimbak Parking Hub',
      'Broadcast hold to field units via radio',
    ],
  },
  {
    alertId: 'a-003',
    type: 'flood',
    severity: 'high',
    zoneId: 'z-001',
    zoneName: 'Ramkund Main Ghat',
    city: 'nashik',
    title: 'Godavari level rising 0.8m in last 2 hours at Ramkund',
    description:
      'IMD reports heavy upstream rainfall. Godavari water level has risen 0.8 metres in the past 2 hours. Ramkund bathing ghat may need closure if trend continues.',
    agentSource: 'FloodWatch',
    status: 'open',
    createdAt: new Date(Date.now() - 360000).toISOString(),
    sopSteps: [
      'Alert Godavari River Authority control room',
      'Position flood response team at Ramkund ghat',
      'Set water-level sensor alert threshold to +1.2m',
      'Prepare ghat evacuation plan',
    ],
  },
  {
    alertId: 'a-004',
    type: 'crowd_surge',
    severity: 'high',
    zoneId: 'z-001',
    zoneName: 'Ramkund Main Ghat',
    city: 'nashik',
    title: 'Crowd surge detected at Ramkund Main Ghat — Red zone',
    description:
      'Crowd density at 6.8 p/sqm, zone declared RED. Entry hold is active. Pilgrims are being redirected to Ramkund West Corridor.',
    agentSource: 'CrowdSentinel',
    status: 'responding',
    createdAt: new Date(Date.now() - 420000).toISOString(),
    acknowledgedBy: 'Sunita Deshmukh',
    sopSteps: [
      'Activate entry hold on Ramkund East Entry',
      'Redirect crowd to West Corridor and Ahilya Ghat',
      'Deploy 15 crowd control personnel at main ghat',
      'Monitor density every 5 minutes until Yellow zone',
    ],
  },
  {
    alertId: 'a-005',
    type: 'medical',
    severity: 'medium',
    zoneId: 'z-009',
    zoneName: 'Kushavart Kund Core',
    city: 'trimbakeshwar',
    title: '3 ambulances dispatched — response time 9 min estimated',
    description:
      'Three medical emergencies reported at Kushavart approach. Three ambulances dispatched from Trimbak Medical Base. ETA 9 minutes.',
    agentSource: 'MedEvac',
    status: 'responding',
    createdAt: new Date(Date.now() - 540000).toISOString(),
    sopSteps: [
      'Clear ambulance lane on NH-848 approach road',
      'Prepare triage area at Trimbak Medical Camp',
      'Alert trauma surgeon on duty',
    ],
  },
  {
    alertId: 'a-006',
    type: 'crowd_surge',
    severity: 'medium',
    zoneId: 'z-010',
    zoneName: 'Kushavart Approach West',
    city: 'trimbakeshwar',
    title: 'Route reroute SMS sent to 48,000 pilgrims away from Kushavart',
    description:
      'RouteOracle has proactively sent SMS notifications to 48,000 pilgrims heading toward Kushavart Kund, advising alternate darshan slots.',
    agentSource: 'RouteOracle',
    status: 'open',
    createdAt: new Date(Date.now() - 600000).toISOString(),
    sopSteps: [
      'Monitor SMS delivery rate (target >95%)',
      'Deploy human guides at Trimbak junction for unregistered pilgrims',
    ],
  },
  {
    alertId: 'a-007',
    type: 'missing',
    severity: 'low',
    zoneId: 'z-010',
    zoneName: 'Kushavart Approach West',
    city: 'trimbakeshwar',
    title: 'Lost child case opened — 6-year-old male, Kushavart approach',
    description:
      'A 6-year-old male child (name: Aryan, wearing blue kurta) was reported missing near Kushavart Approach West at 14:32. Facial recognition scan initiated.',
    agentSource: 'LostConnect',
    status: 'open',
    createdAt: new Date(Date.now() - 900000).toISOString(),
    sopSteps: [
      'Broadcast description over PA at Trimbakeshwar area',
      'Alert all zone personnel with child description',
      'Check camera feeds at Trimbak Parking Hub and approach roads',
    ],
  },
  {
    alertId: 'a-008',
    type: 'flood',
    severity: 'low',
    zoneId: 'z-001',
    zoneName: 'Ramkund Main Ghat',
    city: 'nashik',
    title: 'IMD forecasts 45mm/hr rainfall in next 3 hours for Nashik',
    description:
      'India Meteorological Department has issued a yellow alert for Nashik district. Expected 45mm/hour rainfall in next 3 hours. River level monitoring frequency increased.',
    agentSource: 'FloodWatch',
    status: 'open',
    createdAt: new Date(Date.now() - 1200000).toISOString(),
    sopSteps: [
      'Increase Godavari level monitoring to every 2 minutes',
      'Pre-position flood response equipment at Ramkund',
      'Alert all nashik zone commanders',
    ],
  },
]

export const RESOLVED_ALERTS: Alert[] = [
  {
    alertId: 'r-001',
    type: 'medical',
    severity: 'medium',
    zoneId: 'z-004',
    zoneName: 'Ahilya Ghat',
    city: 'nashik',
    title: 'Pilgrim collapsed at Ahilya Ghat — cardiac event',
    description: 'Elderly pilgrim (male, ~65 years) collapsed. Ambulance responded.',
    agentSource: 'MedEvac',
    status: 'resolved',
    createdAt: new Date(Date.now() - 7200000).toISOString(),
    resolvedAt: new Date(Date.now() - 6900000).toISOString(),
    acknowledgedBy: 'Dr. Anjali Kulkarni',
    sopSteps: [],
  },
  {
    alertId: 'r-002',
    type: 'crowd_surge',
    severity: 'high',
    zoneId: 'z-008',
    zoneName: 'Nashik Bus Terminal',
    city: 'nashik',
    title: 'Bus terminal crowd surge — 5.8 p/sqm peak',
    description: 'Crowd peaked at 5.8 p/sqm during morning auspicious bathing window.',
    agentSource: 'CrowdSentinel',
    status: 'resolved',
    createdAt: new Date(Date.now() - 10800000).toISOString(),
    resolvedAt: new Date(Date.now() - 9000000).toISOString(),
    sopSteps: [],
  },
]

export const GHATS: GhatCondition[] = [
  {
    ghatId: 'g-001',
    name: 'Ramkund Main',
    city: 'nashik',
    status: 'caution',
    waterLevel: 1.2,
    waterLevelTrend: 'rising',
    bathingAllowed: true,
    lastUpdated: new Date(Date.now() - 300000).toISOString(),
    nextUpdateIn: 10,
    riskFactors: ['Rising water level', 'High crowd density', 'Upstream rainfall'],
  },
  {
    ghatId: 'g-002',
    name: 'Ahilya Ghat',
    city: 'nashik',
    status: 'safe',
    waterLevel: 0.4,
    waterLevelTrend: 'stable',
    bathingAllowed: true,
    lastUpdated: new Date(Date.now() - 600000).toISOString(),
    nextUpdateIn: 15,
    riskFactors: [],
  },
  {
    ghatId: 'g-003',
    name: 'Kushavart Kund',
    city: 'trimbakeshwar',
    status: 'caution',
    waterLevel: 0.1,
    waterLevelTrend: 'stable',
    bathingAllowed: true,
    lastUpdated: new Date(Date.now() - 120000).toISOString(),
    nextUpdateIn: 5,
    riskFactors: ['Overcrowding', 'Entry hold active'],
  },
  {
    ghatId: 'g-004',
    name: 'Shriram Ghat',
    city: 'nashik',
    status: 'safe',
    waterLevel: 0.0,
    waterLevelTrend: 'stable',
    bathingAllowed: true,
    lastUpdated: new Date(Date.now() - 900000).toISOString(),
    nextUpdateIn: 20,
    riskFactors: [],
  },
  {
    ghatId: 'g-005',
    name: 'Mukti Dham Ghat',
    city: 'nashik',
    status: 'warning',
    waterLevel: 1.8,
    waterLevelTrend: 'rising',
    bathingAllowed: false,
    lastUpdated: new Date(Date.now() - 180000).toISOString(),
    nextUpdateIn: 5,
    riskFactors: ['Water level critical', 'Strong current', 'Bathing prohibited'],
  },
]

export const AGENTS: Agent[] = [
  {
    agentId: 'ag-001',
    name: 'CommandBridge',
    role: 'Master coordination agent — orchestrates all sub-agents and escalates to human operators',
    status: 'active',
    lastAction: 'Coordinating dual-city emergency response for Kushavart + Ramkund',
    lastActionTime: new Date(Date.now() - 60000).toISOString(),
    invocationsToday: 847,
    alertsRaised: 12,
    model: 'amazon.nova-pro-v1:0',
    averageResponseMs: 198,
    toolsUsed: ['dynamo_read_zone', 'invoke_child_agent', 'send_sns_alert', 'dynamo_write_alert'],
  },
  {
    agentId: 'ag-002',
    name: 'CrowdSentinel',
    role: 'Real-time crowd density analysis — reads camera feeds, raises stampede/surge alerts',
    status: 'alert',
    lastAction: 'Red zone declared at Ramkund + Black zone at Kushavart Kund',
    lastActionTime: new Date(Date.now() - 30000).toISOString(),
    invocationsToday: 2341,
    alertsRaised: 8,
    model: 'amazon.nova-lite-v1:0',
    averageResponseMs: 143,
    toolsUsed: ['camera_feed_read', 'dynamo_read_zone', 'dynamo_write_alert', 'invoke_parent_agent'],
  },
  {
    agentId: 'ag-003',
    name: 'RouteOracle',
    role: 'Pilgrim routing and crowd flow optimization — sends SMS reroutes and manages entry windows',
    status: 'active',
    lastAction: 'Rerouting 48K pilgrims from Kushavart via Trimbak Alternate Road (TAR-2)',
    lastActionTime: new Date(Date.now() - 90000).toISOString(),
    invocationsToday: 1203,
    alertsRaised: 3,
    model: 'amazon.nova-pro-v1:0',
    averageResponseMs: 267,
    toolsUsed: ['sms_bulk_send', 'dynamo_read_zone', 'maps_route_calculate', 'pilgrim_registry_read'],
  },
  {
    agentId: 'ag-004',
    name: 'FloodWatch',
    role: 'River level monitoring and flood risk assessment — integrates IMD data and sensor feeds',
    status: 'active',
    lastAction: 'Monitoring Godavari level every 5 min — rising trend at Ramkund, 1.2m above normal',
    lastActionTime: new Date(Date.now() - 300000).toISOString(),
    invocationsToday: 892,
    alertsRaised: 4,
    model: 'amazon.nova-lite-v1:0',
    averageResponseMs: 189,
    toolsUsed: ['sensor_read_riverlevel', 'imd_api_fetch', 'dynamo_write_alert', 'send_sns_alert'],
  },
  {
    agentId: 'ag-005',
    name: 'MedEvac',
    role: 'Medical emergency coordination — dispatches ambulances, coordinates with hospitals',
    status: 'active',
    lastAction: '3 active dispatches — trauma case at Kushavart approach, ETA 9 min',
    lastActionTime: new Date(Date.now() - 120000).toISOString(),
    invocationsToday: 234,
    alertsRaised: 2,
    model: 'amazon.nova-pro-v1:0',
    averageResponseMs: 312,
    toolsUsed: ['ambulance_dispatch', 'hospital_capacity_check', 'dynamo_write_alert', 'sms_single_send'],
  },
  {
    agentId: 'ag-006',
    name: 'LostConnect',
    role: 'Lost person identification — runs facial recognition against camera feeds and reunites families',
    status: 'idle',
    lastAction: '1 open case (Aryan, 6yr) — facial recognition scan in progress across 47 cameras',
    lastActionTime: new Date(Date.now() - 600000).toISOString(),
    invocationsToday: 156,
    alertsRaised: 2,
    model: 'amazon.nova-lite-v1:0',
    averageResponseMs: 445,
    toolsUsed: ['rekognition_search', 'pilgrim_registry_read', 'sms_single_send', 'dynamo_write_alert'],
  },
]

export const AGENT_LOGS: AgentInvocationLog[] = [
  { logId: 'l-001', timestamp: new Date(Date.now() - 60000).toISOString(), agentName: 'CrowdSentinel', actionTaken: 'Black zone declared — Kushavart Kund Core', zoneAffected: 'Kushavart Kund Core', durationMs: 134, result: 'alert' },
  { logId: 'l-002', timestamp: new Date(Date.now() - 90000).toISOString(), agentName: 'CommandBridge', actionTaken: 'Entry hold activated via DynamoDB write', zoneAffected: 'Kushavart Kund Core', durationMs: 201, result: 'success' },
  { logId: 'l-003', timestamp: new Date(Date.now() - 120000).toISOString(), agentName: 'RouteOracle', actionTaken: 'Bulk SMS sent to 48,212 pilgrims', zoneAffected: 'Kushavart Approach West', durationMs: 287, result: 'success' },
  { logId: 'l-004', timestamp: new Date(Date.now() - 180000).toISOString(), agentName: 'MedEvac', actionTaken: 'Dispatched ambulances KSA-01, KSA-02, KSA-03', zoneAffected: 'Kushavart Kund Core', durationMs: 321, result: 'success' },
  { logId: 'l-005', timestamp: new Date(Date.now() - 240000).toISOString(), agentName: 'FloodWatch', actionTaken: 'Godavari level alert — 1.2m above normal', zoneAffected: 'Ramkund Main Ghat', durationMs: 178, result: 'alert' },
  { logId: 'l-006', timestamp: new Date(Date.now() - 300000).toISOString(), agentName: 'CrowdSentinel', actionTaken: 'Red zone declared — Ramkund Main Ghat', zoneAffected: 'Ramkund Main Ghat', durationMs: 142, result: 'alert' },
  { logId: 'l-007', timestamp: new Date(Date.now() - 360000).toISOString(), agentName: 'LostConnect', actionTaken: 'Facial recognition scan initiated for Aryan (6yr)', zoneAffected: 'Kushavart Approach West', durationMs: 489, result: 'success' },
  { logId: 'l-008', timestamp: new Date(Date.now() - 420000).toISOString(), agentName: 'CommandBridge', actionTaken: 'NDRF notification sent — dual city emergency', zoneAffected: 'All zones', durationMs: 199, result: 'success' },
  { logId: 'l-009', timestamp: new Date(Date.now() - 480000).toISOString(), agentName: 'FloodWatch', actionTaken: 'IMD yellow alert ingested — 45mm/hr forecast', zoneAffected: 'Nashik district', durationMs: 165, result: 'success' },
  { logId: 'l-010', timestamp: new Date(Date.now() - 540000).toISOString(), agentName: 'RouteOracle', actionTaken: 'Calculated alternate route TAR-2 capacity: 12,000/hr', zoneAffected: 'Trimbakeshwar', durationMs: 312, result: 'success' },
]

export const PILGRIMS: Pilgrim[] = [
  { pilgrimId: 'p-001', name: 'Mohan Sharma', age: 58, language: 'hindi', phone: '9876543210', emergencyContact: '9876543211', hasHealthFlag: true, healthNote: 'Hypertension, on medication', currentZoneId: 'z-006', registeredAt: new Date(Date.now() - 86400000).toISOString(), qrCode: 'QR-p-001' },
  { pilgrimId: 'p-002', name: 'Savita Kale', age: 45, language: 'marathi', phone: '9765432109', emergencyContact: '9765432110', hasHealthFlag: false, currentZoneId: 'z-004', registeredAt: new Date(Date.now() - 72000000).toISOString(), qrCode: 'QR-p-002' },
  { pilgrimId: 'p-003', name: 'Arumugam Rajan', age: 67, language: 'tamil', phone: '9654321098', emergencyContact: '9654321099', hasHealthFlag: true, healthNote: 'Diabetic, insulin dependent', currentZoneId: 'z-009', registeredAt: new Date(Date.now() - 54000000).toISOString(), qrCode: 'QR-p-003' },
  { pilgrimId: 'p-004', name: 'Harsha Patel', age: 32, language: 'gujarati', phone: '9543210987', emergencyContact: '9543210988', hasHealthFlag: false, currentZoneId: 'z-001', registeredAt: new Date(Date.now() - 43200000).toISOString(), qrCode: 'QR-p-004' },
  { pilgrimId: 'p-005', name: 'Vijayalakshmi Nair', age: 52, language: 'kannada', phone: '9432109876', emergencyContact: '9432109877', hasHealthFlag: false, currentZoneId: 'z-011', registeredAt: new Date(Date.now() - 36000000).toISOString(), qrCode: 'QR-p-005' },
]

export const LOST_FOUND_CASES: LostFoundCase[] = [
  {
    caseId: 'lf-001',
    type: 'lost',
    name: 'Aryan',
    age: 6,
    description: 'Boy wearing blue kurta and white pyjama. Lost near Kushavart Approach West. Speaks Hindi.',
    lastSeenZone: 'Kushavart Approach West',
    lastSeenTime: new Date(Date.now() - 900000).toISOString(),
    reporterPhone: '9876512345',
    status: 'open',
    reportedAt: new Date(Date.now() - 900000).toISOString(),
    city: 'trimbakeshwar',
  },
  {
    caseId: 'lf-002',
    type: 'found',
    name: 'Unknown elderly woman',
    age: 70,
    description: 'Elderly woman found disoriented at Sadhugram Zone B. Wearing orange saree. No ID on her.',
    lastSeenZone: 'Sadhugram Zone B',
    lastSeenTime: new Date(Date.now() - 3600000).toISOString(),
    reporterPhone: '9765498765',
    status: 'open',
    reportedAt: new Date(Date.now() - 3600000).toISOString(),
    city: 'nashik',
  },
  {
    caseId: 'lf-003',
    type: 'lost',
    name: 'Ramesh Gupta',
    age: 72,
    description: 'Elderly man separated from family at Ramkund East Entry. Wearing saffron dhoti.',
    lastSeenZone: 'Ramkund East Entry',
    lastSeenTime: new Date(Date.now() - 7200000).toISOString(),
    reporterPhone: '9654387654',
    status: 'matched',
    reportedAt: new Date(Date.now() - 7200000).toISOString(),
    city: 'nashik',
  },
]

export const AMBULANCES: Ambulance[] = [
  { vehicleId: 'amb-001', callSign: 'KSA-01', city: 'trimbakeshwar', status: 'dispatched', currentLat: 19.9328, currentLng: 73.5291, assignedIncidentId: 'a-005', crew: 'Dr. Nair + Para Rathod' },
  { vehicleId: 'amb-002', callSign: 'KSA-02', city: 'trimbakeshwar', status: 'dispatched', currentLat: 19.9335, currentLng: 73.5302, assignedIncidentId: 'a-005', crew: 'Dr. Wagh + Para Joshi' },
  { vehicleId: 'amb-003', callSign: 'KSA-03', city: 'trimbakeshwar', status: 'dispatched', currentLat: 19.9319, currentLng: 73.5278, assignedIncidentId: 'a-005', crew: 'Dr. Bhatt + Para Kadam' },
  { vehicleId: 'amb-004', callSign: 'NSK-01', city: 'nashik', status: 'available', currentLat: 20.0010, currentLng: 73.7840, crew: 'Dr. Sawant + Para Mane' },
  { vehicleId: 'amb-005', callSign: 'NSK-02', city: 'nashik', status: 'available', currentLat: 19.9980, currentLng: 73.7855, crew: 'Dr. Kulkarni + Para Pawar' },
]

// Generate hourly density data for zone detail charts
export function getZoneDensityHistory(zone: Zone): { x: string; y: number }[] {
  const history = []
  const now = Date.now()
  for (let i = 6; i >= 0; i--) {
    const ts = new Date(now - i * 3600000)
    const hour = ts.getHours()
    let base = zone.currentDensity * 0.5
    if (i <= 2) base = zone.currentDensity * (0.8 + (2 - i) * 0.1)
    else if (i <= 4) base = zone.currentDensity * 0.6
    history.push({
      x: ts.toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit', hour12: true }),
      y: parseFloat((base + Math.random() * 0.5).toFixed(1)),
    })
  }
  return history
}
